version: '3'

services:
  db:
    container_name: db
    image: centos:7
    tty: true
    stdin_open: true
    networks:
      - back

  node:
    container_name: node
    image: centos:7
    tty: true
    stdin_open: true
    depends_on:
      - db
    networks:
      - back
      - front

  nginx:
    container_name: nginx
    image: centos:7
    tty: true
    stdin_open: true
    depends_on:
      - node
    networks:
      - front

networks:
  back:
  front: